server:
  port: 8095
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
  application:
    name: AdminService
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enableSelfPreservation: false
