server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: CustomerModule
        uri: http://localhost:8091/
        predicates:
        - Path=/customer/**
        
      - id: ReservationModule
        url: http://localhost:8092/
        predicates:
        - Path=/reservations/**
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



